<?php
include "../Model/reponse.php";
include "../Controller/reponseController.php";

if (isset($_POST["reponse"]) && isset($_GET["id"])) {
    if (!empty($_POST["reponse"]) && !empty($_GET["id"])) {
        $reponse = new Reponse(
            $_GET["id"], // Pass the id_reclamation
            null, // id_reponse (auto-generated by the database)
            $_POST["reponse"], // The response text
            date('Y-m-d') // Current date
        );

        $reponsec = new reponseController();
        $reponsec->addReponse($reponse);

        header('Location: http://localhost/productCRUD/reponse/View/mesReponse.php');
        exit();
    } else {
        echo "Erreur : Les champs sont vides.";
    }
}
?>

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajouter Réponse</title>
    <a href="\productCRUD\reclamation\View\mesReclamations.php">BACK</a>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            text-align: center;
            color: #2ecc71;
        }
        label {
            font-weight: bold;
        }
        textarea {
            width: 100%;
            height: 100px;
            margin-bottom: 20px;
            padding: 10px;
            border-radius: 5px;
            border: 1px solid #ccc;
        }
        button {
            background-color: #2ecc71;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            display: block;
            margin: 0 auto;
        }
        button:hover {
            background-color: #27ae60;
        }
    </style>
</head>
<body>
<div class="container">
    <h1>Ajouter Réponse</h1>
    <form action="" method="POST">
        <label for="reponse">Réponse :</label>
        <textarea id="reponse" name="reponse"></textarea>
        <button type="submit">Envoyer la Réponse</button>
    </form>
</div>
</body>
</html>
